version: '3'
name: "scamazon"

networks:
  my_network:
    driver: bridge

services:

  order-processing-service:
    build: ./backend
    networks:
      - my_network

  prometheus-order-processing-service:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    networks:
      - my_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml

  mongo-order-processing-service:
    image: mongo
    restart: always
    volumes:
      - ./data-vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express.order-processing-service:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017//
