version: "3"
name: "scamazon"

networks:
  my_network:
    driver: bridge

volumes:
  mongo-data:


services:
  order-processing-service:
    build: ./backend
    networks:
      - my_network
    ports:
      - "5004:5002"
    depends_on:
      mongo-order-processing-service:
        condition: service_healthy
    environment:
      - DB_PORT=5002
      - DB_USERNAME=root
      - DB_PASSWORD=example

  prometheus-order-processing-service:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - my_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml

  mongo-order-processing-service:
    image: mongo
    restart: always
    networks:
      - my_network
    volumes:
      - ./mongo-data:/data/db
      - ./init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    healthcheck:
      test: echo 'mongo.runCommand("ping").ok' | mongosh mongo-order-processing-service:27017 --quiet
      interval: 50s
      timeout: 50s
      retries: 20
      start_period: 600s
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: allOrders

  mongo-express-order-processing-service:
    image: mongo-express
    restart: always
    ports:
      - 8086:8081
    networks:
      - my_network
    depends_on:
      mongo-order-processing-service:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-order-processing-service:27017/
